### ISSUE TITLE
Strange hiding formatting

### ISSUE THREAD

**Issue by pbrisbin** [lspitzner/brittany#150]
With `brittany-0.11.0.0`, I'm getting the following for a long `hiding` import, is it intentional?

```hs
import Prelude as X
    hiding ( head
    , init
    , last
    , maximum
    , minimum
    , pred
    , read
    , readFile
    , succ
    , tail
    )
```

It looks quite weird to me, I would've expected this:

```hs
import Prelude as X hiding
    ( head
    , init
    , last
    , maximum
    , minimum
    , pred
    , read
    , readFile
    , succ
    , tail
    )
```

Or maybe this:

```hs
import Prelude as X
    hiding
        ( head
        , init
        , last
        , maximum
        , minimum
        , pred
        , read
        , readFile
        , succ
        , tail
        )
```

I'm using this configuration:

```yaml
---
conf_debug:
  dconf_roundtrip_exactprint_only: false
  dconf_dump_bridoc_simpl_par: false
  dconf_dump_ast_unknown: false
  dconf_dump_bridoc_simpl_floating: false
  dconf_dump_config: false
  dconf_dump_bridoc_raw: false
  dconf_dump_bridoc_final: false
  dconf_dump_bridoc_simpl_alt: false
  dconf_dump_bridoc_simpl_indent: false
  dconf_dump_annotations: false
  dconf_dump_bridoc_simpl_columns: false
  dconf_dump_ast_full: false
conf_forward:
  options_ghc: []
conf_errorHandling:
  econf_ExactPrintFallback: ExactPrintFallbackModeInline
  econf_Werror: false
  econf_omit_output_valid_check: false
  econf_produceOutputOnErrors: false
conf_preprocessor:
  ppconf_CPPMode: CPPModeAbort
  ppconf_hackAroundIncludes: false
conf_version: 1
conf_layout:
  lconfig_altChooser:
    tag: AltChooserBoundedSearch
    contents: 3
  lconfig_importColumn: 60
  lconfig_alignmentLimit: 1
  lconfig_indentListSpecial: true
  lconfig_indentAmount: 4
  lconfig_alignmentBreakOnMultiline: true
  lconfig_cols: 80
  lconfig_indentPolicy: IndentPolicyLeft
  lconfig_indentWhereSpecial: true
  lconfig_columnAlignMode:
    tag: ColumnAlignModeDisabled
    contents: 0.7
```
