### ISSUE TITLE
Configuration for minimal diffs (VCS friendly)

### ISSUE THREAD

**Issue by hasufell** [lspitzner/brittany#316]
I think many big projects try to minimize the amount of conflicts they have when merging, rebasing, etc etc, so the main goal is to create as little diff as possible.

One very important aspect of this is: never align identifiers based on other identifiers (except where it is necessary, e.g. for `let`)... because the layout changes too easily on code changes increasing the diff. Also see e.g. https://github.com/input-output-hk/adrestia/wiki/Coding-Standards#avoid-variable-length-indentation

There might be other things to do or avoid. Does anyone have ideas for an ultimate config for this?

**Comment by tfausak** [comment]
I typically use this as a starting point:

``` yaml

**Comment by hasufell** [comment]
I tried it and it leads to weird formatting wrt `let` and `in`.

## Config

```yaml
conf_layout:
  lconfig_columnAlignMode:
    tag: ColumnAlignModeDisabled
  lconfig_indentPolicy: IndentPolicyLeft

  lconfig_importColumn: 50
  lconfig_allowSingleLineExportList: true
  lconfig_importAsColumn: 50
  lconfig_hangingTypeSignature: true
  lconfig_indentListSpecial: true
  lconfig_indentAmount: 4
  lconfig_alignmentBreakOnMultiline: true
  lconfig_cols: 80
  lconfig_indentWhereSpecial: true

conf_forward:
  options_ghc:
  - -XBangPatterns
  - -XDataKinds
  - -XExplicitForAll
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XGADTs
  - -XImplicitParams
  - -XLambdaCase
  - -XMultiWayIf
  - -XPatternGuards
  - -XQuasiQuotes
  - -XRecursiveDo
  - -XTemplateHaskell
  - -XTupleSections
  - -XTypeFamilies
  - -XViewPatterns
```

## Before

```hs
printProject :: PinGHC -> Project -> Maybe Text -> IO Text
printProject (PinGHC pin) (Project (Ghc ghc) pkgs srcs ghcOpts) hack = do
  ghcOpts' <- printGhcOpts ghcOpts
  pure $ T.concat $ [ "-- Generated by stackage-to-hackage\n\n"] <>
         withCompiler <>
         [ "packages:\n    ", packages, "\n\n"
         , sources, "\n"
         , "allow-older: *\n"
         , "allow-newer: *\n"
         ] <> ghcOpts' <> verbatim hack
  where
    withCompiler
      | pin = ["with-compiler: ", ghc, "\n\n"]
      | otherwise = []
    verbatim Nothing = []
    verbatim (Just txt) = ["\n-- Verbatim\n", txt]
    packages = T.intercalate "\n  , " (T.pack . addTrailingPathSeparator <$>
                                     NEL.toList pkgs)
    sources = T.intercalate "\n" (source =<< srcs)
    source Git{repo, commit, subdirs} =
      let base = T.concat [ "source-repository-package\n    "
                        , "type: git\n    "
                        , "location: ", repo, "\n    "
                        , "tag: ", commit, "\n"]
      in if null subdirs
         then [base]
         else (\d -> T.concat [base, "    subdir: ", d, "\n"]) <$> subdirs

    -- Get the ghc options. This requires IO, because we have to figure out
    -- the local package names.
    printGhcOpts (GhcOptions locals _ everything (PackageGhcOpts packagesGhcOpts)) = do
      -- locals are basically pkgs since cabal-install-3.4.0.0
      localsPrint <- case locals of
        Just x -> fmap concat $ forM pkgs $ \pkg -> do
          name <- fmap (unPackageName . pkgName) <$> getPackageIdent pkg
          pure $ maybe []
            (\n -> if M.member n $ M.mapKeys (unPackageName . pkgName . unPkgId)
                                             packagesGhcOpts
                   then []
                   else ["\npackage ", T.pack n, "\n    ", "flags: ", x, "\n"]
            )
            name
        Nothing -> pure []
      let everythingPrint = case everything of
            Just x -> ["\npackage ", "*", "\n    ", "flags: ", x, "\n"]
            Nothing -> []
      let pkgSpecificPrint = M.foldrWithKey
            (\k a b -> ["\npackage "
                       , (T.pack . unPackageName . pkgName . unPkgId $ k)
                       , "\n    "
                       , "flags: "
                       , a
                       , "\n"] <> b)
            [] packagesGhcOpts
      pure (everythingPrint <> localsPrint <> pkgSpecificPrint)
```

## After

```hs
printProject :: PinGHC -> Project -> Maybe Text -> IO Text
printProject (PinGHC pin) (Project (Ghc ghc) pkgs srcs ghcOpts) hack = do
    ghcOpts' <- printGhcOpts ghcOpts
    pure
        $ T.concat
        $ ["-- Generated by stackage-to-hackage\n\n"]
        <> withCompiler
        <> [ "packages:\n    "
           , packages
           , "\n\n"
           , sources
           , "\n"
           , "allow-older: *\n"
           , "allow-newer: *\n"
           ]
        <> ghcOpts'
        <> verbatim hack
  where
    withCompiler
        | pin = ["with-compiler: ", ghc, "\n\n"]
        | otherwise = []
    verbatim Nothing = []
    verbatim (Just txt) = ["\n-- Verbatim\n", txt]
    packages = T.intercalate
        "\n  , "
        (T.pack . addTrailingPathSeparator <$> NEL.toList pkgs)
    sources = T.intercalate "\n" (source =<< srcs)
    source Git { repo, commit, subdirs } =
        let
            base = T.concat
                [ "source-repository-package\n    "
                , "type: git\n    "
                , "location: "
                , repo
                , "\n    "
                , "tag: "
                , commit
                , "\n"
                ]
        in
            if null subdirs
                then [base]
                else
                    (\d -> T.concat [base, "    subdir: ", d, "\n"]) <$> subdirs

    -- Get the ghc options. This requires IO, because we have to figure out
    -- the local package names.
    printGhcOpts (GhcOptions locals _ everything (PackageGhcOpts packagesGhcOpts))
        = do
      -- locals are basically pkgs since cabal-install-3.4.0.0
            localsPrint <- case locals of
                Just x -> fmap concat $ forM pkgs $ \pkg -> do
                    name <- fmap (unPackageName . pkgName)
                        <$> getPackageIdent pkg
                    pure $ maybe
                        []
                        (\n ->
                            if M.member n $ M.mapKeys
                                (unPackageName . pkgName . unPkgId)
                                packagesGhcOpts
                            then
                                []
                            else
                                [ "\npackage "
                                , T.pack n
                                , "\n    "
                                , "flags: "
                                , x
                                , "\n"
                                ]
                        )
                        name
                Nothing -> pure []
            let
                everythingPrint = case everything of
                    Just x -> ["\npackage ", "*", "\n    ", "flags: ", x, "\n"]
                    Nothing -> []
            let
                pkgSpecificPrint = M.foldrWithKey
                    (\k a b ->
                        [ "\npackage "
                            , (T.pack . unPackageName . pkgName . unPkgId $ k)
                            , "\n    "
                            , "flags: "
                            , a
                            , "\n"
                            ]
                            <> b
                    )
                    []
                    packagesGhcOpts
            pure (everythingPrint <> localsPrint <> pkgSpecificPrint)
```
