### ISSUE TITLE
Unclear instructions in README how to build with stack

### ISSUE THREAD

**Issue by vaclavsvejcar** [lspitzner/brittany#362]
I'm trying to build _brittany_ from `master` using _stack_, so I checked readme and it says to use:

> stack install brittany # --resolver lts-16.31

which doesn't seem correct because obviously current version requires _GHC 9.x_. I also tried with latest nightly (`nightly-2022-01-04`) but it doesn't seem to fit as well:

```
Selected resolver: nightly-2022-01-04
Resolver 'nightly-2022-01-04' does not have all the packages to match your requirements.
    aeson version 1.5.6.0 found
        - brittany requires >=2.0.1 && <2.1
    butcher not found
        - brittany requires >=1.3.3 && <1.4
    data-tree-print not found
        - brittany requires >=0.1.0 && <0.2
    multistate not found
        - brittany requires >=0.8.0 && <0.9
    text version 1.2.4.1 found
        - brittany requires >=1.2.5 && <1.3
    Using package flags:
        - brittany: FlagName "pedantic" = False
```

Is actually _brittany_ still intended to be built using any existing _stack resolver_? I know this is probably low priority stuff, but maybe it would be nice to have working _stack.yaml_ to make it easier building _brittany_ using _stack_, if possible?

**Comment by vaclavsvejcar** [comment]
Just fyi, I was able to build `brittany` from `master` (`0aa04af`) using following `stack.yaml`:

```yaml
resolver: nightly-2022-01-15

extra-package-dbs: []

flags: {}

packages:
  - "."

extra-deps:
  - butcher-1.3.3.2
  - data-tree-print-0.1.0.2
  - multistate-0.8.0.3
  - aeson-2.0.3.0
  - yaml-0.11.7.0
  
allow-newer: true
```

Given that _brittany_ is command line tool and not library, maybe the range of supported _GHC_ versions might not be such large and if only one major version will be supported (let's say only `9.0.x`), maybe it might not be that difficult to put together some working `stack.yaml` to make it easier for folks willing to build _brittany_ using _Stack_? If you'd be interested, I can try to help with this.
