### ISSUE TITLE
Indent size sometimes 4 sometimes 2 spaces

### ISSUE THREAD

**Issue by 2dotslash** [lspitzner/brittany#374]
Apologies if this is my mistake

I'm using

    lconfig_indentAmount: 4
    lconfig_indentListSpecial: false

I expect indentation to only ever be 4 spaces, not to mix and match 4 and 2 spaces.

Here's a screenshot.

![Screenshot from 2022-07-28 13-33-37](https://user-images.githubusercontent.com/41240958/181505907-e16f4948-c1fd-4c85-a96e-12a746f00f24.png)

Lines 8-13 are indented by 10 spaces ? I expect it to be 8, and to *never* indent with anything other than a multiple of 4 spaces.

Here's how I expect it to be formatted.

![Screenshot from 2022-07-28 13-35-49](https://user-images.githubusercontent.com/41240958/181506322-2c74bee1-dac9-4812-b0fe-95a41691169c.png)

Here's my full config, I've changed random things trying to get this to work how I expect.
    ~/.config/brittany/config.yaml

```
conf_debug:
  dconf_dump_annotations: false
  dconf_dump_ast_full: false
  dconf_dump_ast_unknown: false
  dconf_dump_bridoc_final: false
  dconf_dump_bridoc_raw: false
  dconf_dump_bridoc_simpl_alt: false
  dconf_dump_bridoc_simpl_columns: false
  dconf_dump_bridoc_simpl_floating: false
  dconf_dump_bridoc_simpl_indent: false
  dconf_dump_bridoc_simpl_par: false
  dconf_dump_config: false
  dconf_roundtrip_exactprint_only: false
conf_disable_formatting: false
conf_errorHandling:
  econf_ExactPrintFallback: ExactPrintFallbackModeInline
  econf_Werror: false
  econf_omit_output_valid_check: false
  econf_produceOutputOnErrors: false
conf_forward:
  options_ghc: []
conf_layout:
  lconfig_alignmentBreakOnMultiline: false
  lconfig_alignmentLimit: 50
  lconfig_allowHangingQuasiQuotes: false
  lconfig_allowSingleLineExportList: false
  lconfig_altChooser:
    contents: 4
    tag: AltChooserBoundedSearch
  lconfig_cols: 120
  lconfig_columnAlignMode:
    contents: 1
    tag: ColumnAlignModeMajority
  lconfig_experimentalSemicolonNewlines: false
  lconfig_hangingTypeSignature: true
  lconfig_importAsColumn: 80
  lconfig_importColumn: 80
  lconfig_indentAmount: 4
  lconfig_indentListSpecial: false
  lconfig_indentPolicy: IndentPolicyLeft
  lconfig_indentWhereSpecial: false
  lconfig_reformatModulePreamble: false
conf_obfuscate: false
conf_preprocessor:
  ppconf_CPPMode: CPPModeAbort
  ppconf_hackAroundIncludes: false
conf_roundtrip_exactprint_only: false
conf_version: 1
```
