### ISSUE TITLE
Brittany can't cope with `-XTupleSections`

### ISSUE THREAD

**Issue by fmthoma** [lspitzner/brittany#41]
Config:

```yaml
…
conf_forward:
  options_ghc:
    - -XLambdaCase
    - -XMultiWayIf
    - -XGADTs
    - -XPatternGuards
    - -XViewPatterns
    - -XRecursiveDo
    - -XTupleSections
    - -XExplicitForAll
    - -XImplicitParams
    - -XQuasiQuotes
    - -XTemplateHaskell
    - -XBangPatterns
…
```

Input:
```haskell
foo = fmap (, ())
```

Error:
```
ERROR: encountered unknown syntactical constructs:
ExplicitTuple|..
```
