### ISSUE TITLE
Syntactically invalid result

### ISSUE THREAD

**Issue by joshbohde** [lspitzner/brittany#98]
Using the `brittany version 0.9.0.0`, the following line of code generates a syntactically invalid result:

```
parseSubOption usage _          _    ("default"   , Nothing) | isJust $ subOptionDefaultValue usage = return $ fromJust $ subOptionDefaultValue usage
```

Using `--output-on-errors`, I get the following output:

```
parseSubOption usage _ _ ("default", Nothing) | isJust $ subOptionDefaultValue usage = return
$ fromJust
$ subOptionDefaultValue usage
```
I'm using the following configuration:

```
conf_version: 1
conf_forward:
  options_ghc: []
conf_preprocessor:
  ppconf_CPPMode: CPPModeAbort
  ppconf_hackAroundIncludes: false
conf_layout:
  lconfig_altChooser:
    tag: AltChooserBoundedSearch
    contents: 300
  lconfig_importColumn: 60
  lconfig_alignmentLimit: 30
  lconfig_indentListSpecial: true
  lconfig_indentAmount: 2
  lconfig_alignmentBreakOnMultiline: true
  lconfig_cols: 120
  lconfig_indentPolicy: IndentPolicyLeft
  lconfig_indentWhereSpecial: false
  lconfig_columnAlignMode:
    tag: ColumnAlignModeMajority
    contents: 0.7
````
